name: Shell cmnds

on: [push, pull_request]

jobs: 
  run-shell-command: 
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "sometinhg...." 
      - name: multiline script
        run: |
          node -v
          npm -v

